### ISSUE TITLE
Reference for immune cells

### ISSUE THREAD

**Issue by phoang1012** [aet21/EpiSCORE#4]
Hello,

Thank you for developing a very helpful tool. I saw in the paper (Teschendorff et al. 2020 Genome Biology) that you also developed a reference matrix for mononuclear cells (monocytes, natural-killer (NK) cells, B cells, CD4+ and CD8+ T cells). Is that reference available for download also? I am interested in deconvolving immune cell contents to smaller subtypes (like the hEpiDISH 7 IC subtypes reference matrix). Would it be possible with the current EpiSCORE reference matrix?

Thank you!

**Comment by aeteschendorff** [comment]
Thanks for your query. For blood or PBMC, it would not make sense to use the EpiSCORE reference matrix, because for these tissues you can easily sort cells and generate DNAm profiles for purified samples (see e.g. Reinius L et al PloS One 2009). So, for these tissues we recommend the DNAm reference matrices that can be found in BioC packages like EpiDISH and minfi!
EpiSCORE is designed for SOLID tissues (where cell-sorting is more challenging), and the inclusion of PBMCs in the paper was just to show "proof-of-principle" that the concept works for a tissue like blood or PBMC. However, the DNAm references in EpiDISH or minfi will work better!
kind regards
A

**Comment by phoang1012** [comment]
Thank you for the clarification!
